apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: consul
    app: consul
  name: consul
spec:
  ports:
    - name: tcp-8300
      port: 8300
      targetPort: 8300
    - name: tcp-8400
      port: 8400
      targetPort: 8400
    - name: tcp-8500
      port: 8500
      targetPort: 8500
    - name: udp-8600
      port: 8600
      protocol: UDP
      targetPort: 53
  selector:
    io.kompose.service: consul
status:
  loadBalancer: {}
