apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socialnetwork-media-frontend
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: mediafrontend.mahwish.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: media-frontend
                port:
                  number: 8081