apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socialnetwork-nginx
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: nginx.mahwish.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-thrift
                port:
                  number: 8080
